#Builder Stage

FROM python:3.11 AS builder

WORKDIR /wheels

COPY requirements.txt ./

RUN pip wheel --no-cache-dir -r requirements.txt 

#Runtime Stage

FROM python:3.11-slim

WORKDIR /app

COPY --from=builder /wheels /wheels

RUN pip install --no-cache-dir --no-index --find-links=/wheels /wheels/*

COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]