#Builder Stage
FROM python:3.11 AS builder 

WORKDIR /wheels

RUN apt-get update && apt-get install -y \
    gcc \
    libffi-dev \
    libssl-dev \
    python3-dev \
 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./

RUN pip wheel --no-cache-dir -r requirements.txt

#Runtime Stage
FROM python:3.11-slim

COPY --from=builder /wheels /wheels 

WORKDIR /app

RUN pip install --no-cache-dir --no-index --find-links=/wheels -r /wheels/requirements.txt

COPY . .

RUN useradd -m -u 10001 appuser \
    && mkdir -p /app/logs \
    && chown -R appuser:appuser /app

USER appuser

EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=3s --retries=3 \
  CMD python -c "import http.client; c=http.client.HTTPConnection('127.0.0.1',8000); c.request('GET','/health'); r=c.getresponse(); exit(0 if r.status==200 else 1)"

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]