FROM python:3.11-alpine 

WORKDIR /app

COPY requirements.txt ./

RUN apk add --no-cache --virtual .build-deps gcc musl-dev libffi-dev python3-dev openssl-dev

RUN pip install --no-cache-dir -r requirements.txt

RUN apk del .build-deps

COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]